
# output: list of products
GET localhost:8080/api/v1/products

###
# param: product id (path variable)
# output: a spesific product in json format
GET localhost:8080/api/v1/products/642aa4df4b8f782cb962f974

###
# param: product json object
# output: product id (string)
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{"name": "acer laptop", "description": "nitro 5", "tags": ["laptop", "pc", "acer"], "category": {
  "name": "laptop", "description": "nothing"
}}

###
# param: product json object
# output: product id (string)
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{"name": "mac book", "description": "apple laptop", "tags": ["laptop", "pc", "apple"], "category": {
  "id": "642a9ea6329c63248c00cbab"
},
  "price": 1200, "quantity": 10, "rating": 4.5
}

###
# request param: product name (string)
# output: list of product in json format
GET localhost:8080/api/v1/products/search/is?name=a

###
# request param: product name (string)
# output: list of product in json format
GET localhost:8080/api/v1/products/search/start-with?name=a

###
# request param: product name (string)
# output: list of product in json format
GET localhost:8080/api/v1/products/search/end-with?name=e

###
# request param: price (BigDecimal)
# output: list of product in json format
GET localhost:8080/api/v1/products/search/lt?price=1300

###
# request param: price (BigDecimal)
# output: list of product in json format
GET localhost:8080/api/v1/products/search/gt?price=1100

###
# request param: field (string)
# output: list of product in json format (asc sorted)
GET localhost:8080/api/v1/products/sort/asc?field=price

