
# output: list of products
GET localhost:8080/api/v1/products

###
# param: product id (path variable)
# output: a spesific product in json format
GET localhost:8080/api/v1/products/642aa4df4b8f782cb962f974

###
# param: product json object
# output: product id (string)
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{"name": "acer laptop", "description": "nitro 5", "tags": ["laptop", "pc", "acer"], "category": {
  "name": "laptop", "description": "nothing"
}}

###
# param: product json object
# output: product id (string)
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{"name": "test", "description": "test ", "tags": ["test"], "category": {
  "id": "642a9ea6329c63248c00cbab"
}}
